---
config:
  theme: 'dark'
---
timeline
	title Scientific Method vs. Computer Science
	Observe: Read the code : Try the software
	Research: Check docs : Learn the stack
	Hypothesize: Reason about code : Make tests: Make changes
	Test: Unit test: Integration test : etc
	Analyze: Check test results: Attempt build/deploy
	Report: Show others in a PR: See if changes accomplish the goal
